### ISSUE TITLE
Enhancement - Encrypted PDF template

### ISSUE THREAD

**Issue by MarkusMad** [georgjf/SMTPtool#1]
Add a template "Encrypted PDF File"

**Comment by georgjf** [comment]
Hi 

I have added an eml template with a password encrypted PDF file attached.
You can download it via the [template page in the wiki](https://github.com/georgjf/SMTPtool/wiki/Remail-Templates).
Please let me know if you have any further ideas or requirements :)

Regards
Georg

**Comment by georgjf** [comment]
Available in the wiki and included in the next release.
